parameters:
    aLangs: ["fr","en"]
    default_lang : "fr"

services:
    annotations_reader_brut:
        class:        Doctrine\Common\Annotations\AnnotationReader
    annotations_apc:
        class:        Doctrine\Common\Cache\ApcCache 
        
    annotations_reader:
        class:          Doctrine\Common\Annotations\CachedReader
        arguments:    ["@annotations_reader_brut","@annotations_apc",true]
      
    entity_item_service:
        class:        Fredb\AdminBundle\Services\AdministrableEntity\EntityItemService
        arguments:    ["@doctrine.orm.entity_manager"]
      
    row_factory:
        class:        Fredb\AdminBundle\Services\Row\RowFactory    
        arguments:    ["@doctrine.orm.entity_manager", "@entity_item_service"]
    admin_form_service:
        class:        Fredb\AdminBundle\Services\AdminFormService    
        arguments:    ["@annotations_reader","@doctrine.orm.entity_manager","@row_factory"]
    annotations_zgroupe_service:
        class:        Fredb\Services\AnnotationsServices
        arguments:    ["@annotations_reader"]
    admin_class_service:
        class:        Fredb\AdminBundle\Services\AdminClassService    
        arguments:    ["@annotations_reader","@doctrine.orm.entity_manager","@row_factory",%aLangs%]
        
    pictures_service:
        class:        Fredb\AdminBundle\Services\AdministrableEntity\FO\PicturesService    
        arguments:    ["@doctrine.orm.entity_manager", "@entity_item_service", "@annotations_reader"]
        
    link_service:
        class:        Fredb\AdminBundle\Services\AdministrableEntity\FO\LinkService    
        arguments:    ["@doctrine.orm.entity_manager", "@entity_item_service", "@annotations_reader"]        
        
    lang_service:
        class:        Fredb\AdminBundle\Services\AdministrableEntity\FO\LangService    
        arguments:    ["@doctrine.orm.entity_manager", "@annotations_reader"]    