language: php

php:
  - 5.3

before_script:
  - composer install --dev
  - phpenv config-add Tests/config.ini
  - "mysql -e 'create database admin_annotation;'"
  
script: phpunit --coverage-text

notifications:
  email:
    - frederic.bourbigot@gmail.com